version: "3.0"

services:
  mongo_db:
    image: mongo
    container_name: mongo_database
    ports:
      - 27017:27017
    volumes:
      - personalweb:/data/configdb
      - personalweb:/data/db

volumes:
  mongopersonalweb: {}